# Generated by Django 4.2.15 on 2024-09-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Erro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_erro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_topico', models.ImageField(upload_to='img/icon_topic/')),
                ('nome_topico', models.CharField(max_length=50)),
                ('introducao', models.TextField()),
                ('imagem', models.ImageField(upload_to='img/image_topic/')),
                ('fonte_topic', models.URLField()),
                ('nivel_experiencia', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=100)),
                ('ferramentas', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='topicos', to='home.categoria')),
                ('funcao', models.ManyToManyField(related_name='topicos', to='home.areaatuacao')),
            ],
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('mensagem', models.TextField()),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_erro', to='home.erro')),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ferramenta', models.CharField(max_length=50)),
                ('imagem_ferramenta', models.ImageField(upload_to='img/image_ferramenta/')),
                ('informacao_ferramenta', models.TextField()),
                ('link_ferramenta', models.URLField()),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.topico')),
            ],
        ),
    ]
