# Generated by Django 5.0.6 on 2024-05-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_topico', models.CharField(max_length=50)),
                ('introducao', models.TextField()),
                ('imagem', models.ImageField(upload_to='img/')),
                ('fonte', models.URLField()),
                ('texto_ferramenta', models.TextField()),
                ('fonte_ferramenta', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ferramenta', models.CharField(max_length=50)),
                ('imagem_ferramenta', models.ImageField(upload_to='img/ferramenta/')),
                ('informacao_ferramenta', models.TextField()),
                ('link_ferramenta', models.URLField()),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.topico')),
            ],
        ),
    ]
