# Generated by Django 4.2.15 on 2024-10-14 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='informacao_ferramenta',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='topico',
            name='introducao',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nivel_experiencia',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=100),
        ),
    ]
