# Generated by Django 5.0.6 on 2024-05-27 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_topico_icon_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_erro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('mensagem', models.TextField()),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_erro', to='home.erro')),
            ],
        ),
    ]
